version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      # Install hatch
      - pip install hatch
    post_install:
      # Install dependencies
      - pip install .[doc]

submodules:
  include: all
