version: 2

sphinx:
  configuration: source/conf.py

formats: all

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
        - doc

submodules:
  include: all
