version: 2

sphinx:
  configuration: docs/source/conf.py
  builder: html

formats: all

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
      # Install hatch
      - pip install hatch
    post_install:
      # Install dependencies
      - pip install .[doc]

submodules:
  include: all
