name: all

on: 
  push:

jobs:
    build:
      runs-on: ubuntu-latest
      container:
        image: apnpucky/ubuntu-pip
      steps:
        - name: work around permission issue
          run: git config --global --add safe.directory /__w/smpl/smpl
        - uses: actions/checkout@v2
          with:
            fetch-depth: "0"
        - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        - run: make build
        - run: make install
        - run: make test
        - name: Build Sphinx
          run: rm -rf build && make clean-all && make html
        - uses: actions/upload-artifact@v3
          with:
            name: coverage 
            path: coverage.xml
        - uses: actions/upload-artifact@v3
          with:
            name: dist
            path: dist
        - uses: actions/upload-artifact@v3
          with:
            name: build
            path: build

    report:
      runs-on: ubuntu-latest
      container:
        image: apnpucky/ubuntu-pip
      name: Report coverage
      if: github.event_name != 'pull_request'
      needs: build
      steps:
        - uses: actions/download-artifact@v3
          with:
            name: coverage  
        - name: Report Coveralls
          uses: AndreMiras/coveralls-python-action@develop
        - name: Report Codacy
          if: github.event_name != 'pull_request'
          uses: codacy/codacy-coverage-reporter-action@v1
          with:
            project-token: ${{ secrets.CODACY_API_TOKEN }}
            coverage-reports: coverage.xml
        
    pypi:
      runs-on: ubuntu-latest
      container:
        image: apnpucky/ubuntu-pip
      name: Deploy PyPi
      if: github.event_name != 'pull_request'
      needs: build
      steps:
        - uses: actions/download-artifact@v3
          with:
            name: dist
            path: dist
        - name: Deploy Test PyPI
          if: github.ref == 'refs/heads/master'
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.test_pypi_token }}
            repository_url: https://test.pypi.org/legacy/
        - name: Deploy PyPI
          if: startsWith(github.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.pypi_token }}

    ghpages:
      runs-on: ubuntu-latest
      container:
        image: apnpucky/ubuntu-pip
      name: Deploy Github Pages
      if: github.event_name != 'pull_request'
      needs: build
      steps:
        - name: work around permission issue
          run: git config --global --add safe.directory /__w/smpl/smpl
        - uses: actions/checkout@v2
          with:
            fetch-depth: "0"
        - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        - uses: actions/download-artifact@v3
          with:
            name: build
            path: build
        - name: Deploy Test Github Pages
          if: github.ref == 'refs/heads/master'
          uses: JamesIves/github-pages-deploy-action@4.1.5
          with:
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: build/html # The folder the action should deploy.
            target-folder: test
        - name: Deploy Github Pages
          if: startsWith(github.ref, 'refs/tags')
          uses: JamesIves/github-pages-deploy-action@4.1.5
          with:
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: build/html # The folder the action should deploy.
            clean-exclude: test/
