name: devel

on: 
  push:
    branches-ignore:
      - 'master'
      - 'stable'
    tags-ignore: 
      - '*'

jobs:
    devel:
      runs-on: ubuntu-latest
      container:
        image: apnpucky/ubuntu-pip
      steps:
        - name: work around permission issue
          run: git config --global --add safe.directory /__w/smpl/smpl
        - uses: actions/checkout@v3
          with:
            fetch-depth: "0"
        - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        - name: Build smpl
          run: make build
        - name: Install smpl
          run: make install
        - name: Tests
          run: make test
        - name: Build Sphinx
          run: rm -rf build && make clean-all && make html
