name: Ubuntu

on:
    push:
        branches: [ master ]
        tags: 
          - '*'
jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: casperdcl/deploy-pypi@v1
          if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
          with:
            password: ${{ secrets.pypi_token }}
            build: true