name: Ubuntu

on: push
jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: "0"
        - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        - name: Set up Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: 3.7
        - name: Install setup and wheel
          run: python3.7 -m pip install --user --upgrade setuptools wheel
        - name: Build a binary wheel and a source tarball
          run: python3.7 setup.py sdist bdist_wheel
        - name: Publish distribution 📦 to Test PyPI
          if: startsWith(github.ref, 'refs/tags') != true
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.test_pypi_token }}
            repository_url: https://test.pypi.org/legacy/
        - name: Publish distribution 📦 to PyPI
          if: startsWith(github.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.pypi_token }}
        - name: Instll (nb)sphinx
          run: sudo apt-get install ipython3 jupyter-notebook
        - name: Install sphinx
          run: sudo pip3 install -U sphinx nbsphinx

        - name: Test install smpl+dependencies
          run: python3 -m pip install smpl
        - name: Run sphinx
          run: make clean html
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            #ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: build # The folder the action should deploy.