name: release

on: 
  push:
    tags: 
      - '*'

jobs:
    build:
      runs-on: ubuntu-latest
      container:
        image: apnpucky/ubuntu-poetry
      steps:
        - uses: APN-Pucky/make-python-action@main
          with:
            test: true
            doc: true
            coveralls: true
            codacy-api-token: ${{ secrets.CODACY_API_TOKEN }}
            pypi-token: ${{ secrets.pypi_token }}
            gh-pages: true
            gh-pages-folder: docs/build/html
