name: test

on: 
  push:
    branches:
      - '*'
    tags-ignore: 
      - '*'

jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: "0"
        - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        - name: Set up Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: 3.7
        - name: Install setup and wheel
          run: python3 -m pip install --user --upgrade setuptools wheel
        - name: Build a binary wheel and a source tarball
          run: python3 setup.py sdist bdist_wheel
        - name: Publish distribution 📦 to Test PyPI
          if: startsWith(github.ref, 'refs/tags') != true
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.test_pypi_token }}
            repository_url: https://test.pypi.org/legacy/
        - run: sudo apt-get update --fix-missing
        - name: Install (nb)sphinx
          run: sudo apt-get install ipython3 jupyter-notebook python3-scipy python3-matplotlib python3-pandas python3-numpy python3-requests python3-uncertainties python3-tqdm python3-numpy 
        - name: Install sphinx
          run: python3 -m pip install -U sphinx nbsphinx numpydoc sphinx-math-dollar 
        - name: Test install smpl+dependencies
          run: python3 -m pip install --index-url https://test.pypi.org/simple/ -U smpl
          #run: make install
        - name: Run sphinx
          run: make clean && make html
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            #ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: build/html # The folder the action should deploy.
            target-folder: test
