name: Ubuntu

on:
    push:
        branches: [ master ]
jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: casperdcl/deploy-pypi@v1
          if: github.event_name == 'push' 
          with:
            password: ${{ secrets.test_pypi_token }}
            build: true