name: test

on: 
  push:
    branches:
      - 'master'
    tags-ignore: 
      - '*'

jobs:
    unstable:
      runs-on: ubuntu-latest
      container:
        image: apnpucky/ubuntu-poetry
      steps:
        - uses: APN-Pucky/make-python-action@main
          with:
            test: true
            doc: true
            coveralls: true
            codacy-api-token: ${{ secrets.CODACY_API_TOKEN }}
            test-pypi-token: ${{ secrets.test_pypi_token }}
            test-gh-pages: true
            gh-pages-folder: docs/build/html
