name: test

on: 
  push:
    branches:
      - 'test'
    tags-ignore: 
      - '*'

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: "0"
        - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        - name: Set up Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: 3.7
        - name: Install setup and wheel
          run: python3 -m pip install --user --upgrade setuptools wheel
        - name: Build a binary wheel and a source tarball
          run: python3 setup.py sdist bdist_wheel
        - run: sudo apt-get update --fix-missing
        - name: Install (nb)sphinx
          run: sudo apt-get install python3-numpy pandoc
        - name: Install sphinx
          run: python3 -m pip install -U sympy tqdm matplotlib scipy jupyterlab pandas uncertainties sphinx nbsphinx numpydoc sphinx-math-dollar sphinx-rtd-theme pytest  pytest-coverage
        - name: Test install smpl+dependencies
          run: python3 -m pip install --index-url https://test.pypi.org/simple/ -U smpl
          #run: make install
        - name: Unit tests
          run: make test
        - name: Coveralls
          uses: AndreMiras/coveralls-python-action@develop
        - name: Run codacy-coverage-reporter
          uses: codacy/codacy-coverage-reporter-action@v1
          with:
            project-token: ${{ secrets.CODACY_API_TOKEN }}
            # or
            #api-token: ${{ secrets.CODACY_API_TOKEN }}
            coverage-reports: coverage.xml

    pypi:
      runs-on: ubuntu-latest
      needs: test
      container:
        image: apnpucky/ubuntu
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: "0"
        - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        - name: Build a binary wheel and a source tarball
          run: python3 setup.py sdist bdist_wheel
        - name: Publish distribution 📦 to Test PyPI
          if: startsWith(github.ref, 'refs/tags') != true
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.test_pypi_token }}
            repository_url: https://test.pypi.org/legacy/

    sphinx:
      runs-on: ubuntu-latest
      #needs: pypi
      container:
        image: apnpucky/ubuntu
      steps:
        - name: Test install smpl+dependencies
          run: python3 -m pip install matplotlib
        - name: Test install smpl+dependencies
          run: python3 -m pip install --index-url https://test.pypi.org/simple/ -U smpl
          #run: make install
        - name: Run sphinx
          run: rm -rf build && make clean-all && make html
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@4.1.5
          with:
            #ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: build/html # The folder the action should deploy.
            target-folder: test
